version: '3'

tasks:
  up:
    cmds:
      - nix flake update
  hmsw: # home-manager switch
    cmds:
      - nix run nixpkgs#home-manager -- switch --flake .#{{env "NAME"}}
  dwsw: # nix-darwin switch
    cmds:
      - nix run nix-darwin -- switch --flake .#marisa
  dwhmsw:
    cmds:
      - nix run nixpkgs#home-manager -- switch --flake .#marisa
  gc:
    cmds:
      - nix-collect-garbage --delete-old
