version: '3'
interval: 100ms

tasks:
  build:
    sources:
      - 'main.cpp'
    cmds:
      - g++ main.cpp -std=gnu++20 -O2 -Wall -Wextra

  test:
    watch: true
    deps: [build]
    sources:
      - 'main.cpp'
    cmds:
      - oj t -d './tests'
